name: cassettemusic
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  audioplayers: ^0.15.0
  provider: 4.0.0
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/ic_slider.png
    - assets/images/ic_turn_arrow.png
    - assets/images/ic_turn_arrow_background.png
    - assets/images/ic_back.png
    - assets/images/ic_next.png
    - assets/images/ic_pause.png
    - assets/images/ic_playing.png
    - assets/images/ic_tmp1.png
    - assets/images/ic_tmp2.png
    - assets/images/ic_play.png
    - assets/images/ic_pauseing.png
    - assets/images/ic_thumb.png
    - assets/images/ic_bg_circle_volume.png
    - assets/images/ic_circle_blue.png
    - assets/images/app_background.png
    - assets/images/bg_bang.png
    - assets/images/bg_mo.png
    - assets/images/bg_mo.png
    - assets/images/ic_next_press.png
    - assets/images/ic_backpress.png

    - assets/audio.mp3